vim.opt.showtabline = 0
vim.opt.clipboard = "unnamedplus"
vim.opt.incsearch = true
vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.pumheight = 10
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undofile = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.breakindent = true
vim.opt.signcolumn = "yes"
vim.opt.scrolloff = 8
vim.opt.ruler = true

